version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8016:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "8015:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
