version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8016:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8015:8015"
    depends_on:
      - backend
